### ISSUE TITLE
DB::NetException

### ISSUE THREAD

**Issue by alifpay** [killwort/ClickHouse-Net#141]
## Description
Unhandled exception. ClickHouse.Ado.ClickHouseException: DB::NetException: Unexpected packet from client (no user in Hello package)

at ClickHouse.Ado.Impl.ProtocolFormatter.ReadAndThrowException()
   at ClickHouse.Ado.Impl.ProtocolFormatter.Handshake(ClickHouseConnectionSettings connectionSettings)
   at ClickHouse.Ado.ClickHouseConnection.Open()

## Steps to reproduce
docker container.  
 "Host=127.0.0.1;Port=9001;"

```cs
 var settings = new ClickHouseConnectionSettings(connStr);
            var cnn = new ClickHouseConnection(settings);
            cnn.Open();
```

**Comment by alifpay** [comment]
connection string


 "Host=127.0.0.1;Port=9001;Database=default;User=default;Password="
 
 this is working
