### ISSUE TITLE
Unable to cast object of type 'System.DBNull' to type 'System.String'

### ISSUE THREAD

**Issue by RomanOlegovich** [killwort/ClickHouse-Net#144]
## Description
In ClickHouse column is Nullable(String). Inserting of any string or null cause error
```
System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.String'.
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ClickHouse.Ado.Impl.ColumnTypes.StringColumnType.ValuesFromConst(IEnumerable objects)
   at ClickHouse.Ado.Impl.ColumnTypes.ColumnType.NullableValuesFromConst(IEnumerable objects)
   at ClickHouse.Ado.Impl.ColumnTypes.NullableColumnType.ValuesFromConst(IEnumerable objects)
   at ClickHouse.Ado.ClickHouseCommand.Execute(Boolean readResponse, ClickHouseConnection connection)
   at ClickHouse.Ado.ClickHouseCommand.ExecuteNonQuery()
```

**Comment by killwort** [comment]
Use `(string)null` value.

**Comment by RomanOlegovich** [comment]
@killwort 
Not it not work.

```
        class ClickHouseTypeConverter : IBulkInsertEnumerable
        {
            private readonly IReadOnlyList<Dictionary<string, object>> data;

            public ClickHouseTypeConverter(IReadOnlyList<Dictionary<string, object>> data)
            {
                this.data = data;
            }

            public IEnumerable<object?> GetColumnData(int colNumber, string columnName, string schemaType)
            {
                if (data.Count == 0)
                    yield break;

                var dataIndex = 0;
                while (dataIndex < data.Count)
                {
                    var value = this.data[dataIndex++][columnName.ToLower()];

                    if (schemaType == "Nullable(String)" && value.GetType() == typeof(DBNull))
                        yield return (string)null;
                    if (value.GetType() == typeof(sbyte))
                        yield return Convert.ToSByte(value);
                    else
                        yield return value;

                }
            }

        }
```

**Comment by RomanOlegovich** [comment]
Excuse for troubling.  there was a bug in using IEnumerable, not all types were converted.
