### ISSUE TITLE
Select statement with UUID type field fails with System.ArgumentException

### ISSUE THREAD

**Issue by skuzminoff** [killwort/ClickHouse-Net#55]
## Description
Select query fails, when there are UUID type fields in fields list. 

## Steps to reproduce
1. Set up database and fiill it with some test data
```
CREATE DATABASE test_uuid

USE test_uuid

CREATE TABLE contains_uuid

CREATE TABLE contains_uuid (
 id UUID,
 name String
)
ENGINE = Log()

INSERT INTO contains_uuid (id, name) VALUES ('b79d6111-f72a-46f4-81ff-62c16edb573e', 'test1'), ('b79d6111-f72a-52f4-81ff-62c16edb573e', 'test2')
```
2. Then 
```
public static void SelectWithUuidFields()
        {
            using (var cnn = GetConnection())
            using (var cmd = cnn.CreateCommand("SELECT id, name FROM contains_uuid"))
            {
                using (var reader = cmd.ExecuteReader())
                {
                    PrintData(reader);
                }
            }

        }

        private static void PrintData(IDataReader reader)
        {
            do
            {
                Console.Write("Fields: ");
                for (var i = 0; i < reader.FieldCount; i++)
                {
                    Console.Write("{0}:{1} ", reader.GetName(i), reader.GetDataTypeName(i));
                }
                Console.WriteLine();
                while (reader.Read())
                {
                    for (var i = 0; i < reader.FieldCount; i++)
                    {
                        var val = reader.GetValue(i);
                        if (val.GetType().IsArray)
                        {
                            Console.Write('[');
                            Console.Write(string.Join(", ", ((IEnumerable) val).Cast<object>()));
                            Console.Write(']');
                        }
                        else
                        {
                            Console.Write(val);
                        }
                        Console.Write(", ");
                    }
                    Console.WriteLine();
                }
                Console.WriteLine();
            } while (reader.NextResult());
        }
```
and
```
 reader.NextResult()
```
throws an exception 
```
System.ArgumentException: 'Object must be an array of primitives.'
```

StackTrace
```
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at ClickHouse.Ado.Impl.ColumnTypes.GuidColumnType.Read(ProtocolFormatter formatter, Int32 rows)
   at ClickHouse.Ado.Impl.Data.ColumnInfo.Read(ProtocolFormatter formatter, Int32 rows)
   at ClickHouse.Ado.Impl.Data.Block.Read(ProtocolFormatter formatter)
   at ClickHouse.Ado.Impl.ProtocolFormatter.ReadPacket(Response rv)
   at ClickHouse.Ado.Impl.ProtocolFormatter.ReadBlock()
   at ClickHouse.Ado.ClickHouseDataReader.NextResult()
   at ConsoleApp2.Program.PrintData(IDataReader reader) in .\Program.cs:line 113
   at ConsoleApp2.Program.SelectWithUuidFields() in .\Program.cs:line 77
   at ConsoleApp2.Program.Main(String[] args) in .\Program.cs:line 41
```

4. In the same time, if we modify the query to 
```
"SELECT id, name FROM contains_uuid"
```
no exception will be thrown and list of string field values will be printed.

Other requisites:
-  net core 2.1 console application
- "ClickHouse.Ado" nuget package  version="1.1.13"

**Comment by killwort** [comment]
Well, Guids cannot be read with BulkCopy. Reimplemented it with value-by-value reading.
