### ISSUE TITLE
DB::Exception

### ISSUE THREAD

**Issue by Haza85** [killwort/ClickHouse-Net#63]
Hi. I have application with log data in ClickHouse database with code some like this
```
private ClickHouseConnection GetConnection()
 {
   var settings = new ClickHouseConnectionSettings("Host=...;Port=...;Database=Data;User=default");
   var chn = new ClickHouseConnection(settings);
   chn.Open();
   return chn;
}
...
using (var chn = GetConnection())
{
   var cmd = chn.CreateCommand($"INSERT INTO ... values...");
   cmd.ExecuteNonQuery();
}
```
Insert command runs ~10 times per second. But every 2-5 minutes I get exception in log:
```
DB::Exception: Timeout exceeded while receiving data from client. Waited for 300 seconds, timeout is 300 seconds.
StackTrace
   at ClickHouse.Ado.Impl.ProtocolFormatter.ReadAndThrowException()
   at ClickHouse.Ado.Impl.ProtocolFormatter.ReadPacket(Response rv)
   at ClickHouse.Ado.Impl.ProtocolFormatter.ReadResponse()
   at ClickHouse.Ado.ClickHouseCommand.Execute(Boolean readResponse, ClickHouseConnection connection)
   at ClickHouse.Ado.ClickHouseCommand.ExecuteNonQuery()
```
Is any ideas why this happen?

**Comment by killwort** [comment]
Could you check clickhouse server logs for errors too?
Most probably that your network is a bit unstable (e.g. there's packet loss) causing some connections to break.

**Comment by killwort** [comment]
Sadly I cannot work on non-reproducible issue.
