### ISSUE TITLE
System.NotSupportedException: 'Unknown column type LowCardinality(String)'

### ISSUE THREAD

**Issue by mkhatuntcov-korewireless** [killwort/ClickHouse-Net#87]
## Description
Looks like this library doesn't support LowCardinality Data Type as of now.

Additional Information:
https://www.altinity.com/blog/2019/3/27/low-cardinality

(this is a placeholder for a few days) I am going to try to implement this myself if I will have resources.

**Comment by killwort** [comment]
Well, this type really lacks documentation :)
And clickhouse team has plans to reimplement it differently:
https://clickhouse.tech/docs/ru/extended_roadmap/#perevod-lowcardinality-iz-datatype-v-column-dobavlenie-columnsparse

**Comment by VitaliyMF** [comment]
@killwort it seems current implementation of "lowCardinality(...)" is what we already have in ClickHouse  releases: https://clickhouse.tech/docs/en/sql-reference/data-types/lowcardinality/

 It should be handled somehow in ClickHouse.Ado. Do you have any plans to add a support of "lowCardinality" data type?

**Comment by killwort** [comment]
I'll consider supporting this type in the next release. Currently i have no eta for it.

**Comment by VitaliyMF** [comment]
Exception stacktrace:
```
---> System.NotSupportedException: Unknown column type LowCardinality(String)
at ClickHouse.Ado.Impl.ColumnTypes.ColumnType.Create(String name)
at ClickHouse.Ado.Impl.Data.ColumnInfo.Read(ProtocolFormatter formatter, Int32 rows)
```

Maybe "LowCardinality(String)" can be handled as an existing "String" datatype? So it should be treated just as an alternative type name.

**Comment by mkhatuntcov-korewireless** [comment]
Apologize for not responding. There is my update.
The issue resolution has been deprioritized a year ago.  
Doesn't look like my management currently interested in addressing this. 
If they are going to change their minds I will spend my team efforts on fixing this. 
As of now I will keep this issue open (as recognized); unless, you guys want to close this, due to no activity.

**Comment by killwort** [comment]
@VitaliyMF i doubt that it could be handled as String type, in the docs they say it was specifically designed to store values as dictionary. And in the native proto serialisation is done in the same way it is done for storage

**Comment by VitaliyMF** [comment]
It seems [this ClickHouse Python Driver](https://github.com/mymarilyn/clickhouse-driver) uses binary protocol and it is already supports LowCardinality with these commits:

- https://github.com/mymarilyn/clickhouse-driver/commit/8a69cbff879772f78c059296b68cf036c967cd7a
- https://github.com/mymarilyn/clickhouse-driver/commit/8df7f9a3fb0af9c1d61c8f919dc89d110359902b

Unfortunately I'm not familiar with Python, but these commits doesn't look very complex.

**Comment by killwort** [comment]
Hah, this type is implemented quite differently from the older types. No more dynamically-sized integers, they're all 8-byte-longs now.

**Comment by Tjon92** [comment]
> Hah, this type is implemented quite differently from the older types. No more dynamically-sized integers, they're all 8-byte-longs now.

Привет!
Спасибо за поддержку LowCardinality.

К сожалению запросы, где присутствуют поля LowCardinality(Nullable(String)) просто зависают, даже не выдавая никаких ошибок. Я пробовал как через ReadAll так и через reader.NextResult().

Как я понимаю для поддержки Nullable в данном типе необходима дополнительная доработка. Очень надеюсь на скорый ответ, так как не могу продолжить работу над проектом.

Спасибо!

**Comment by killwort** [comment]
Не то чтобы у меня было много времени на доработки, я обычно раз в 3-4 месяца сажусь и делаю всё накопившееся.

Да, Nullable внутри LowCardinality реализованы как-то особенно, я в детали пока не очень вникал. В целом картина такая, что любые LowCardinality на самом деле являются Nullable, так как словарь значений всегда содержит пустое значение.

При желании, можете помочь исправить - PR-ы я принимаю быстро.

**Comment by Tjon92** [comment]
То есть я правильно понимаю, что в ближайшие дни/недели точно не стоит ждать исправления? Я пытался вникнуть и сделать PR, но для меня это темный лес. 

Я лишь могу предположить, что в файле ColumnType.cs нужно сделать, что-то типа того как для Array:
                    case "Array":
                        if (m.Groups["inner"].Value == "Null")
                            return new ArrayColumnType(new NullableColumnType(new SimpleColumnType<byte>()));
                        return new ArrayColumnType(Create(m.Groups["inner"].Value));
                        
Я задаю этот вопрос просто для понимания стоит ждать или нет, а не пытаясь вас убедить.
